from __future__ import annotations

from typing import Any


SOURCE_REGISTRY: list[dict[str, Any]] = [
    {
        "id": "alforaij_board",
        "name": "الفريج - بيانات اللوحة المحلية",
        "category": "مصدر أساسي",
        "connection": "ملف بيانات محلي",
        "role": "يدخل في البحث والمطابقة والتقييم",
        "trustLevel": "مرتفع داخل حدود بيانات الفريج",
        "scoringPolicy": "يدخل في درجة المطابقة والتقييم عند توفر السعر/المساحة/الرابط.",
        "evidencePolicy": "كل نتيجة تحتفظ برابط الإعلان الأصلي والحقول الخام عند توفرها.",
        "status": "connected",
    },
    {
        "id": "opensooq_kw",
        "name": "OpenSooq Kuwait",
        "category": "سوق إعلانات خارجي",
        "connection": "بحث حي من صفحة النتائج العامة",
        "role": "يدخل في البحث والتقييم بعد فلترة النوع والمنطقة والعملية",
        "trustLevel": "متوسط",
        "scoringPolicy": "لا يدخل الإعلان إلا إذا كان تصنيفه عقاريًا ويطابق الطلب صراحة.",
        "evidencePolicy": "الرابط والسعر والمنطقة والوصف تحفظ كمصدر لكل رقم مستخرج.",
        "status": "live_scored",
    },
    {
        "id": "mourjan_kw",
        "name": "Mourjan Kuwait",
        "category": "سوق إعلانات خارجي",
        "connection": "قراءة HTML من صفحة البحث العامة",
        "role": "يدخل في البحث والتقييم عند وجود كارت إعلان مطابق",
        "trustLevel": "متوسط",
        "scoringPolicy": "يتم تحديد نوع العقار من مسار الإعلان، وليس من طلب المستخدم.",
        "evidencePolicy": "الرابط والوصف والسعر الصريح تدخل كدليل عند توفرها.",
        "status": "live_scored",
    },
    {
        "id": "q8aqar",
        "name": "Q8Aqar",
        "category": "دليل عقاري كويتي",
        "connection": "صفحات منطقة/نوع العقار العامة + قراءة صفحات التفاصيل",
        "role": "يدخل في البحث والتقييم عند إثبات نفس الطلب، ويُحسَّن السعر/المساحة من صفحة التفاصيل",
        "trustLevel": "متوسط، أعلى عند قراءة صفحة التفاصيل نفسها",
        "scoringPolicy": "إذا لم يثبت الإعلان أنه نفس المنطقة والنوع والعملية لا يدخل في التقييم.",
        "evidencePolicy": "السعر والمساحة يُستخرجان من العنوان ثم تُقرأ صفحات التفاصيل لتحسينهما عند توفرها.",
        "status": "live_scored",
    },
    {
        "id": "sakan",
        "category": "بوابة بحث عقاري",
        "name": "Sakan",
        "connection": "فحص صفحة البحث العامة + محاولة قراءة الحالة المضمّنة في الصفحة",
        "role": "يُستخرج من الحالة المضمّنة عند توفرها، وإلا يبقى دليل توفر وعدد متاح",
        "trustLevel": "متوسط عند استخراج إعلانات مضمّنة قابلة للتحقق، منخفض عند عدم توفرها",
        "scoringPolicy": "لا يدخل في الدرجة إلا بعد استخراج إعلانات تفصيلية تثبت نفس الطلب.",
        "evidencePolicy": "يعرض عدد المتاح ورابط الصفحة، مع إعلانات مستخرجة عند ظهورها في الحالة المضمّنة.",
        "status": "live_conditional",
    },
    {
        "id": "official_transactions",
        "name": "الصفقات الرسمية / التسجيل العقاري",
        "category": "مصدر رسمي",
        "connection": "جدول official_transactions في Supabase + ملف data/official_transactions.json",
        "role": "المصدر الأقوى لتقييم السعر: وسيط مرجح أعلى من الإعلانات عند توفر صفقات",
        "trustLevel": "مرتفع جدًا",
        "scoringPolicy": "يُستخدم كمرجع سوقي مرجح أولًا قبل المعيار الرسمي والإعلانات عند توفر صفقات بنفس المنطقة.",
        "evidencePolicy": "يحفظ رقم/تاريخ الصفقة والمنطقة والنوع والمساحة والسعر ووسيط سعر المتر المشتق.",
        "status": "connected",
    },
    {
        "id": "nabdaqar",
        "name": "نبض عقار (NabdAqar)",
        "category": "منصة عقارية كويتية",
        "connection": "بحث حي وتنقيب HTML في الإعلانات المباشرة",
        "role": "يدخل في البحث والمطابقة والتقييم عند توفر بيانات الإعلان",
        "trustLevel": "مرتفع (منصة عقارية كويتية متخصصة)",
        "scoringPolicy": "يدخل في التقييم بحسب السعر والمواصفات المستخرجة.",
        "evidencePolicy": "يتمفظ برابط الإعلان والنص الأصلي كدليل.",
        "status": "connected",
    },
    {
        "id": "bu3qar",
        "name": "بوعقار / بوشملان (Bu3qar)",
        "category": "منصة عقارية كويتية",
        "connection": "بحث حي واستخراج من نتائج بوعقار",
        "role": "يدخل في البحث والمطابقة والتقييم",
        "trustLevel": "مرتفع (سوق كويتي نشط)",
        "scoringPolicy": "يدخل في التقييم عند استخراج السعر والمساحة صراحة.",
        "evidencePolicy": "يرتبط مباشرة برابط العقار كدليل.",
        "status": "connected",
    },
    {
        "id": "waseet",
        "name": "وسيط الكويت (Waseet)",
        "category": "سوق إعلانات خارجي",
        "connection": "قراءة HTML من صفحة البحث العامة",
        "role": "يدخل في البحث والمطابقة عند توفر بطاقة إعلان",
        "trustLevel": "متوسط",
        "scoringPolicy": "يدخل في التقييم عند استخراج السعر والمنطقة.",
        "evidencePolicy": "الرابط والنص الأصلي يُحفظان كدليل عند توفرهما.",
        "status": "connected",
    },
    {
        "id": "aqarat",
        "name": "Aqarat",
        "category": "مصادر توسعة",
        "connection": "بحث حي من صفحة البحث العامة",
        "role": "يدخل في البحث والتقييم عند ظهور إعلان يثبت نفس الطلب",
        "trustLevel": "متوسط",
        "scoringPolicy": "تدخل بنفس قواعد الفلترة والدليل (المنطقة والنوع والعملية).",
        "evidencePolicy": "كل نتيجة تحفظ الرابط والنص الأصلي كدليل.",
        "status": "live_conditional",
    },
    {
        "id": "four_sale",
        "name": "4Sale",
        "category": "مصادر توسعة",
        "connection": "بحث حي من صفحة البحث العامة",
        "role": "يدخل في البحث والتقييم عند ظهور إعلان يثبت نفس الطلب",
        "trustLevel": "متوسط",
        "scoringPolicy": "تدخل بنفس قواعد الفلترة والدليل.",
        "evidencePolicy": "كل نتيجة تحفظ الرابط والنص الأصلي كدليل.",
        "status": "live_conditional",
    },
    {
        "id": "other_marketplaces",
        "name": "منصات أخرى: مصادر مكاتب / API مستقبلية",
        "category": "مصادر توسعة",
        "connection": "API/Feed عند توفره من شريك",
        "role": "لا تدخل في التقييم إلا بعد مصدر بيانات مستقر",
        "trustLevel": "غير محدد حتى الربط",
        "scoringPolicy": "تدخل تدريجيًا بنفس قواعد الفلترة والدليل.",
        "evidencePolicy": "كل مصدر جديد يجب أن يمر من سجل تشغيل وتوثيق رابط/رقم الإعلان.",
        "status": "planned",
    },
]


def source_registry() -> list[dict[str, Any]]:
    return [dict(item) for item in SOURCE_REGISTRY]
